[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  VITE_API_URL = "https://mmeraki-backend1.vercel.app/api"

[[redirects]]
  from = "/api/*"
  to = "https://mmeraki-backend1.vercel.app/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

